### PR TITLE
improved command macro

### PR DESCRIPTION
**Pull request by planetis-m**
Unlike the previous attempt, it keeps the api intact. Also it's faster than const tables and generates less code bloat.

### CODE REVIEW

**Comment by jyapayne** [comment]
This looks largely the same as the previous attempt, albeit with the same API as the original. I'm still unconvinced that the case statement is faster than the table. Can you come up with a benchmark to illustrate?

Also, you'll probably need to add a nimble install of `fusion` to the [test.yml](https://github.com/halonium/halonium/blob/master/.github/workflows/test.yml) in order for the CI to be happy.

**Comment by planetis-m** [comment]
Don't need a new benchmark, we have benchmarked case statements with string vs tables countless times. Case statements are always faster. See https://github.com/nim-lang/Nim/pull/16438#pullrequestreview-557443878 it has benchmarks you can try.

**Comment by jyapayne** [comment]
Yes, the effort is definitely appreciated! And thank you for the explanation. I wasn't aware case/switch statements were so efficient. Not sure if you linked the proper issue (I don't see any mention of case statements or benchmarks, but I didn't look that closely), but I did my own investigation and I will now use case statements in place of hash tables where appropriate. 

Everything else looks good!

**Comment by planetis-m** [comment]
Hi! Thank you for merging, I appreciate it! Press "Show resolved" in the previous link to see the discussion.

**Pull request merged**
